# Generated by Django 5.0.6 on 2024-05-25 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Project name")),
                ("description", models.TextField(verbose_name="Project desription")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=50, verbose_name="Customer name"),
                ),
                (
                    "projects",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TimeManagmentApp.project",
                        verbose_name="Customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Task name")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Task description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO_DO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                        ],
                        default="TO_DO",
                        help_text="Task status",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=0, verbose_name="Priority (0-5)"),
                ),
                ("due_date", models.DateTimeField(verbose_name="Should be done")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TimeManagmentApp.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TimeManagmentApp.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=6, unique=True)),
                (
                    "car_model",
                    models.CharField(max_length=50, verbose_name="Car model"),
                ),
                ("car_make", models.CharField(max_length=50, verbose_name="Car make")),
                ("capacity", models.IntegerField(default=5, verbose_name="Capacity")),
                (
                    "project",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TimeManagmentApp.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=255, verbose_name="Role")),
                ("skills", models.TextField(verbose_name="Skills")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ISA", "Available"),
                            ("ONV", "On vacation"),
                            ("ONS", "On working site"),
                            ("OFF", "On the way home"),
                            ("ONW", "On the way to work"),
                            ("NOT", "Not Available"),
                        ],
                        default="NOT",
                        help_text="Worker availability status",
                        max_length=3,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TimeManagmentApp.project",
                    ),
                ),
                ("tasks", models.ManyToManyField(to="TimeManagmentApp.task")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
