# Generated by Django 5.0.6 on 2024-05-25 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TimeManagmentApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="project",
        ),
        migrations.AlterField(
            model_name="customer",
            name="projects",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="TimeManagmentApp.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(5)],
                verbose_name="Priority (0-5)",
            ),
        ),
    ]
