# Generated by Django 5.0.6 on 2024-05-25 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "TimeManagmentApp",
            "0002_remove_task_project_alter_customer_projects_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(5)],
                verbose_name="Priority (0-5)",
            ),
        ),
    ]
