# Generated by Django 5.0.6 on 2024-05-25 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TimeManagmentApp", "0004_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="capacity",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(8),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Capacity",
            ),
        ),
    ]
