# Generated by Django 5.0.6 on 2024-05-25 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TimeManagmentApp", "0010_remove_vehicle_workers_vehicle_workers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="workers",
        ),
        migrations.AddField(
            model_name="worker",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TimeManagmentApp.vehicle",
            ),
        ),
    ]
