# Generated by Django 5.0.6 on 2024-05-27 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TimeManagmentApp", "0013_project_place_city_alter_project_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="TimeManagmentApp.project",
            ),
        ),
    ]
