# Generated by Django 5.0.6 on 2024-05-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TimeManagmentApp", "0014_alter_worker_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="worker",
        ),
        migrations.AddField(
            model_name="task",
            name="worker",
            field=models.ManyToManyField(blank=True, to="TimeManagmentApp.worker"),
        ),
    ]
