# Generated by Django 5.0.6 on 2024-05-28 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "TimeManagmentApp",
            "0016_remove_customer_projects_remove_task_project_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="customers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="TimeManagmentApp.customer",
                verbose_name="Customer",
            ),
        ),
    ]
