# Generated by Django 5.0.6 on 2024-05-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TimeManagmentApp", "0017_alter_project_customers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="customers",
            new_name="customer",
        ),
    ]
