# Generated by Django 5.0.6 on 2024-05-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TimeManagmentApp", "0018_rename_customers_project_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("TODO", "To Do"), ("INPS", "In Progress"), ("DONE", "Done")],
                default="TO_DO",
                help_text="Task status",
                max_length=20,
            ),
        ),
    ]
