# Generated by Django 5.0.6 on 2024-05-31 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TimeManagmentApp", "0020_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="project",
            name="project_end",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="project_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
