# Generated by Django 5.0.6 on 2024-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TimeManagmentApp", "0022_worker_availability_date_alter_worker_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="picture",
            field=models.ImageField(
                blank=True, default="no-image.png", upload_to="project_pics"
            ),
        ),
    ]
