# Generated by Django 5.0.6 on 2024-06-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TimeManagmentApp", "0025_vehicle_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="duration_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Duration (hours)",
            ),
        ),
    ]
