# Generated by Django 5.0.6 on 2024-06-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TimeManagmentApp", "0026_task_duration_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="duration_hours",
            field=models.IntegerField(default=0, verbose_name="Duration (hours)"),
        ),
    ]
